### ISSUE TITLE
insert_spotify_uri: Cannot read property 'EU' of undefined

### ISSUE THREAD

**Issue by Boostflow** [hklages/node-red-contrib-sonos-plus#39]
I'm trying to add a Spotify element (track, album, playlist etc) to the queue using the examples provided in the wiki. 

element used: `[{"id":"8d0b193b.cc2258","type":"inject","z":"99e6906e.c69df","name":"spotify track","topic":"spotify:track:5AdoS3gS47x40nBNlNmPQ8","payload":"insert_spotify_uri","payloadType":"str","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":1167,"y":1149,"wires":[["c02b5a3d.f2fbb8"]]}]`

Output
"TypeError: Cannot read property 'EU' of undefined"

Is this a misconfiguration on my end or part of your improvements to the notification system?

**Comment by hklages** [comment]
Hi. It is a bug.

Have a look at 2.1.9
It should fix that issue.

**Comment by dr-boss** [comment]
In 2.1.9 the error still exist. 
After send topic for example to"Sauna Music (Relaxing Music for Sauna) – Wellness" (sure, exist on spotify), payload to insert_spotify the Query Node return "TypeError: Cannot read property 'EU' of undefined"

**Comment by hklages** [comment]
yes - you are right. I will fix it in 4.1.10 

I suggest that you use "Manage My Sonos"  instead of "Manage Queue".  That should already work now. 

What is the difference: The `insert_spotify` is a special command and does a lot of tricky things. It may break in the future. 
The `queue` command in " Manage My Spotify" is more robust and also supports Napster, ...

**Comment by dr-boss** [comment]
thx, I will change to My Sonos for testing, BTW I things You will fix in 2.1.10 not in 4.1.10 because in this case we wait very long or You plan very fast development many of editions ;-)

**Comment by hklages** [comment]
:-) yes 4.1.0 is some month ahead 

... as a mathematician sometimes numbers are difficult for me. 

2.1.10 has already been published. Hopefully 3.0.0 will come next week with better notification and group handling.

**Comment by dr-boss** [comment]
Thx, for super work and a lot of health these days

**Comment by hklages** [comment]
Thanks for the feedback. 
Health for you too!
I close this issue.
